# Generated by Django 2.0.3 on 2018-03-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlueHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MoviesCurrentlyShowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_hall_movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviehalls.BlackHall')),
                ('blue_hall_movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviehalls.BlueHall')),
            ],
        ),
        migrations.CreateModel(
            name='MoviesRedHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_image', models.ImageField(upload_to='static/images/movieImages')),
                ('showtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RedHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='moviesredhall',
            name='movies_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviehalls.RedHall'),
        ),
        migrations.AddField(
            model_name='moviescurrentlyshowing',
            name='red_hall_movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviehalls.RedHall'),
        ),
    ]
