# Generated by Django 2.0.3 on 2018-03-31 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviehalls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_image', models.ImageField(upload_to='static/images/movieImages')),
                ('showtime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='moviesredhall',
            name='movies_hall',
        ),
        migrations.AddField(
            model_name='blackhall',
            name='movies_black_hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moviehalls.Halls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bluehall',
            name='movies_blue_hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moviehalls.Halls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halls',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='redhall',
            name='movies_red_hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moviehalls.Halls'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MoviesRedHall',
        ),
        migrations.AddField(
            model_name='halls',
            name='movies_showing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moviehalls.Movies'),
            preserve_default=False,
        ),
    ]
