# Generated by Django 2.0.3 on 2018-03-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviehalls', '0002_auto_20180331_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviehalls.Movies')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviehalls.Halls')),
            ],
        ),
    ]
