# Generated by Django 2.0.3 on 2018-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehalls', '0003_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserved',
            name='seat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
