# Generated by Django 2.0.3 on 2018-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehalls', '0005_auto_20180401_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
