# Generated by Django 2.0.3 on 2018-04-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehalls', '0006_auto_20180401_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackhall',
            name='hall_name',
            field=models.CharField(default='Black_hall', max_length=30),
        ),
        migrations.AddField(
            model_name='bluehall',
            name='hall_name',
            field=models.CharField(default='Blue_hall', max_length=30),
        ),
        migrations.AddField(
            model_name='redhall',
            name='hall_name',
            field=models.CharField(default='Red_hall', max_length=30),
        ),
    ]
