# Generated by Django 2.0.3 on 2018-04-02 13:42

import apps.moviehalls.renamefile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehalls', '0008_auto_20180402_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_image',
            field=models.ImageField(upload_to=apps.moviehalls.renamefile.UploadToPathAndRename('static/images/movieImages')),
        ),
    ]
